
services:
  web:
    image: app-name:latest
    build:
      target: web
      context: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - /var/www/html/.env
    depends_on:
      - db

  db:
    platform: "linux/amd64"
    image: mysql:8.0  # Changed to a valid MySQL version
    env_file:
      - .env.db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: