name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/SCRUM-62-initialize-the-ci-cd-pipeline

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0  # Corrected to a stable MySQL version
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: laravel_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # Checking out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Setting up PHP environment for Laravel
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: pdo_mysql
          coverage: none
          tools: composer

      # Caching Composer dependencies
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('fireX/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      # Waiting for MySQL to be healthy
      - name: Wait for MySQL to be ready
        run: |
          for i in {1..10}; do
            if mysqladmin ping -h127.0.0.1 --silent; then
              echo "MySQL is ready!";
              break;
            fi
            echo "Waiting for MySQL to be ready...";
            sleep 5;
          done

      # Installing dependencies in the 'fireX' directory
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
        working-directory: ./fireX

      # Setting up environment file
      - name: Set up environment file
        run: |
          cp fireX/.env.example fireX/.env  
          php artisan key:generate
        working-directory: ./fireX

      # Running Laravel migrations
      - name: Run migrations
        run: php artisan migrate --force
        working-directory: ./fireX

      # Running Laravel tests
      - name: Run tests
        run: php artisan test
        working-directory: ./fireX

      # Cleanup
      - name: Clean up dependencies
        run: |
          composer clear-cache
        working-directory: ./fireX
