name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/SCRUM-62-initialize-the-ci-cd-pipeline
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:9.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: laravel_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up PHP environment
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: pdo_mysql
          tools: composer

      # Debug directory structure
      - name: Verify file paths
        run: |
          echo "Listing root directory:"
          ls -la
          echo "Listing fireX directory:"
          ls -la fireX/

      # Install dependencies
      - name: Install Composer dependencies
        working-directory: fireX
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      # Verify existence of .env file
      - name: Ensure .env file exists
        run: |
        
          if [ ! -f fireX/.env ]; then
            cp fireX/.env.example fireX/.env
            exit 1;
          fi
          echo ".env file found."

      # Set Laravel app environment
      - name: Set environment variables
        working-directory: fireX
        env:
          APP_ENV: local
        run: |
          php artisan config:clear
          php artisan cache:clear
          php artisan key:generate

      # Run database migrations
      - name: Run migrations
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel_db
          DB_USERNAME: root
          DB_PASSWORD: rootpassword
        run: php artisan migrate --force

      # Run application tests
      - name: Run tests
        working-directory: fireX
        run: php artisan test
