name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_DATABASE }}
          MYSQL_USER: ${{ secrets.DB_USERNAME }}
          MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
       
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Compose
      - name: Set up Docker Compose
        run: |
          cd fireX
          docker-compose up -d --build

      # Wait for MySQL to be ready
      - name: Wait for MySQL
        run: |
          for i in {1..10}; do
            if docker exec firex-db mysqladmin ping -h"db" --silent; then
              echo "MySQL is ready!";
              break;
            fi
            echo "Waiting for MySQL...";
            sleep 5;
          done

      # Run Laravel Artisan commands
      - name: Run Artisan Commands
        run: |
          docker exec firex-app php artisan migrate --force
          docker exec firex-app php artisan test
