name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:9.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: laravel_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # Checking out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Setting up PHP environment for Laravel
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: pdo_mysql
          tools: composer

      # Caching Composer dependencies
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      # Debugging file structure
      - name: Debug file paths
        run: ls -la fireX/

      # Installing dependencies
      - name: Install dependencies
        working-directory: fireX
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      # Setting up the .env file and generating the application key
      - name: Set up environment file
        working-directory: fireX
        run: |
          php artisan config:clear
          php artisan cache:clear
          php artisan key:generate

      # Running Laravel migrations
      - name: Run migrations
        working-directory: fireX
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel_db
          DB_USERNAME: root
          DB_PASSWORD: rootpassword
        run: php artisan migrate --force

      # Running Laravel tests
      - name: Run tests
        working-directory: fireX
        run: php artisan test

      # Cleanup Composer cache
      - name: Clean up dependencies
        run: composer clear-cache
