name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/*  # This will trigger for any feature branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:9.0 # Keeping MySQL version as per your local setup
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: laravel_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up PHP environment for Laravel (PHP 8.3)
      - name: Set up PHP with Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: pdo_mysql, mbstring, exif, bcmath
          tools: composer

      # Cache Composer dependencies to speed up future builds
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      # Wait for MySQL to be ready
      - name: Wait for MySQL to be ready
        run: |
          for i in {1..10}; do
            if mysqladmin ping -h127.0.0.1 --silent; then
              echo "MySQL is ready!"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 5
          done

      # Install Composer dependencies
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
        working-directory: ./
      

      # Set up .env file from example and generate the application key
      - name: Set up environment file
        run: |
          cp .env.example .env
          php artisan key:generate

      # Run Laravel migrations
      - name: Run migrations
        run: php artisan migrate --force

      # Run Laravel tests
      - name: Run tests
        run: php artisan test

      # Clean up Composer cache to save space
      - name: Clean up dependencies
        run: composer clear-cache
